# Sorting, Counting, Querying

We often have a large dataset but we are only interested in smaller sections of it.

Or we want to sort from largest to smallest.

Or perhaps we want to know how many instances of some value there is in the data.

Tonight we finally move beyond the basics to see the start of data analysis.

## Import libraries

In [8]:
## import libraries
import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [9]:
## import summer data
dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [10]:
## import winter data
## import winter data
dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

## Get a sense of the data

In [11]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.
dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [12]:
## WINTER
## what exactly do we have: columns, datatypes, etc.
dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

In [13]:
## Create a dataframe that for only summer games years and cities
subset_of_full_data_df = dfw[["Year", "City", "Sport"]]
subset_of_full_data_df

       Year      City                 Sport
0      1924  Chamonix            Ice Hockey
1      1924  Chamonix       Nordic Combined
2      1924  Chamonix           Ski Jumping
3      1924  Chamonix  Cross Country Skiing
4      1924  Chamonix       Nordic Combined
...     ...       ...                   ...
48559  2014     Sochi         Alpine Skiing
48560  2014     Sochi         Alpine Skiing
48561  2014     Sochi         Alpine Skiing
48562  2014     Sochi           Ski Jumping
48563  2014     Sochi           Ski Jumping

[48564 rows x 3 columns]

In [14]:
dfs.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze' " ).value_counts().to_frame("Quantity").sort_values(by="Quantity", ascending = True)

                                                                                                                                                                               Quantity
ID     Athlete Name                   Sex Age  Height Weight Team          NOC Year City           Sport               Event                                           Medal
16616  Thomas Edmund "Tom" Burke      M   21.0 183.0  66.0   United States USA 1896 Athina         Athletics           Athletics Men's 100 metres                      Gold           1
109437 Courtney Amanda Shealy (-Hart) F   22.0 191.0  72.0   United States USA 2000 Sydney         Swimming            Swimming Women's 4 x 100 metres Freestyle Relay Gold           1
109425 Roman Anatoliyovych Shchurenko M   23.0 188.0  82.0   Ukraine       UKR 2000 Sydney         Athletics           Athletics Men's Long Jump                       Bronze         1
109281 Sergey Aleksandrovich Sharikov M   26.0 182.0  78.0   Russia        RUS 2000 Sydney         Fencing             Fencing Men's Sabre, Team                       Gold           1
109185 Yelena Vladimirovna Shalamova  F   18.0 176.0  51.0   Russia        RUS 2000 Sydney         Rhythmic Gymnastics Rhythmic Gymnastics Women's Group               Gold           1
...                                                                                                                                                                                 ...
73506  Zoltn Magyar                   M   26.0 165.0  60.0   Hungary       HUN 1980 Moskva         Gymnastics          Gymnastics Men's Team All-Around                Bronze         1
73345  Michele Maffei                 M   33.0 178.0  79.0   Italy         ITA 1980 Moskva         Fencing             Fencing Men's Sabre, Team                       Silver         1
73244  Djan Garrido Madruga           M   21.0 181.0  69.0   Brazil        BRA 1980 Moskva         Swimming            Swimming Men's 4 x 200 metres Freestyle Relay   Bronze         1
73019  Lutz Mack                      M   27.0 168.0  65.0   East Germany  GDR 1980 Moskva         Gymnastics          Gymnastics Men's Team All-Around                Silver         1
135525 Martin Zwicker                 M   29.0 175.0  64.0   Germany       GER 2016 Rio de Janeiro Hockey              Hockey Men's Hockey                             Bronze         1

[25341 rows x 1 columns]

In [15]:
dfs.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze' " ).value_counts(ascending = False).to_frame("Quantity")

                                                                                                                                                                  Quantity
ID     Athlete Name                    Sex Age  Height Weight Team          NOC Year City           Sport      Event                                      Medal
16616  Thomas Edmund "Tom" Burke       M   21.0 183.0  66.0   United States USA 1896 Athina         Athletics  Athletics Men's 100 metres                 Gold           1
                                                                                                               Athletics Men's 400 metres                 Gold           1
22700  James Brendan Bennet Connolly   M   27.0 175.0  72.0   United States USA 1896 Athina         Athletics  Athletics Men's High Jump                  Silver         1
                                                                                                               Athletics Men's Long Jump                  Bronze         1
                                                                                                               Athletics Men's Triple Jump                Gold           1
...                                                                                                                                                                    ...
134857 Zhu Ting                        F   21.0 198.0  78.0   China         CHN 2016 Rio de Janeiro Volleyball Volleyball Women's Volleyball              Gold           1
135132 Bojana ivkovi                   F   28.0 186.0  72.0   Serbia        SRB 2016 Rio de Janeiro Volleyball Volleyball Women's Volleyball              Silver         1
135205 Shakhobiddin Shokirovich Zoirov M   23.0 169.0  52.0   Uzbekistan    UZB 2016 Rio de Janeiro Boxing     Boxing Men's Flyweight                     Gold           1
135245 Milenko Zori                    M   27.0 179.0  73.0   Serbia        SRB 2016 Rio de Janeiro Canoeing   Canoeing Men's Kayak Doubles, 1,000 metres Silver         1
135525 Martin Zwicker                  M   29.0 175.0  64.0   Germany       GER 2016 Rio de Janeiro Hockey     Hockey Men's Hockey                        Bronze         1

[25341 rows x 1 columns]

In [16]:
dfs.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze' " ).value_counts(ascending = True)

ID      Athlete Name                     Sex  Age   Height  Weight  Team           NOC  Year  City            Sport       Event                                       Medal
16616   Thomas Edmund "Tom" Burke        M    21.0  183.0   66.0    United States  USA  1896  Athina          Athletics   Athletics Men's 100 metres                  Gold      1
                                                                                                                          Athletics Men's 400 metres                  Gold      1
22700   James Brendan Bennet Connolly    M    27.0  175.0   72.0    United States  USA  1896  Athina          Athletics   Athletics Men's High Jump                   Silver    1
                                                                                                                          Athletics Men's Long Jump                   Bronze    1
                                                                                                                          Athletics Men's Triple Jump                 Gold      1
                                                                                                                                                                               ..
134857  Zhu Ting                         F    21.0  198.0   78.0    China          CHN  2016  Rio de Janeiro  Volleyball  Volleyball Women's Volleyball               Gold      1
135132  Bojana ivkovi                    F    28.0  186.0   72.0    Serbia         SRB  2016  Rio de Janeiro  Volleyball  Volleyball Women's Volleyball               Silver    1
135205  Shakhobiddin Shokirovich Zoirov  M    23.0  169.0   52.0    Uzbekistan     UZB  2016  Rio de Janeiro  Boxing      Boxing Men's Flyweight                      Gold      1
135245  Milenko Zori                     M    27.0  179.0   73.0    Serbia         SRB  2016  Rio de Janeiro  Canoeing    Canoeing Men's Kayak Doubles, 1,000 metres  Silver    1
135525  Martin Zwicker                   M    29.0  175.0   64.0    Germany        GER  2016  Rio de Janeiro  Hockey      Hockey Men's Hockey                         Bronze    1
Name: count, Length: 25341, dtype: int64

Homework Challenge
1. How many medals were handed out in winter games v. summer game (return both in absolutes and as a percentage)?
2. Top 10 count of gold medals by country
3. Of these top 10, what percent of the gold medals do they have?

In [19]:
## Medals handed out in summer games
dfs["Medal"].value_counts(ascending = False).to_frame("Quantity")

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

        Quantity
Medal
Gold       11459
Bronze     11409
Silver     11220

In [21]:
## Medals handed out in winter games
dfw["Medal"].value_counts(ascending = False).to_frame("Quantity")

        Quantity
Medal
Gold        1913
Silver      1896
Bronze      1886

In [22]:
dfs["Season"] = "summer"
dfs.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer

In [25]:
## In the winter dataframe, add "Season" column with the value "Winter"
dfw["Season"] = "winter" 
dfw.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter

In [26]:
dfw.columns

Index(['ID', 'Athlete Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC',
       'Year', 'City', 'Sport', 'Event', 'Medal', 'Season'],
      dtype='str')

In [27]:
dfw.columns ==  dfs.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [28]:
## join winter and summer dataframes together into a dataframe called df
# df = pd.concat([dfs,dfw]) ## Led to the wrong total index. 
df = pd.concat([dfs,dfw], ignore_index = True)
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [29]:
summer_df = df.query("Season == 'summer'")
summer_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [30]:
summer_df.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze' " ).sort_values(by="Medal")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
222546,135525,Martin Zwicker,M,29.0,175.0,64.0,Germany,GER,2016,Rio de Janeiro,Hockey,Hockey Men's Hockey,Bronze,summer
83989,44344,Andrea Gyarmati (-Hesz),F,18.0,170.0,64.0,Hungary,HUN,1972,Munich,Swimming,Swimming Women's 100 metres Butterfly,Bronze,summer
83994,44399,Ileana Gyulai-Drmb-Jenei,F,26.0,164.0,61.0,Romania,ROU,1972,Munich,Fencing,"Fencing Women's Foil, Team",Bronze,summer
84008,44668,Reinhard Hfner,M,20.0,174.0,62.0,East Germany,GDR,1972,Munich,Football,Football Men's Football,Bronze,summer
84023,44891,Ulla Margareta Mileva Hkansson (Svenfelt-),F,34.0,170.0,55.0,Sweden,SWE,1972,Munich,Equestrianism,"Equestrianism Mixed Dressage, Team",Bronze,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104582,93981,Petko Petkov,M,22.0,200.0,84.0,Bulgaria,BUL,1980,Moskva,Volleyball,Volleyball Men's Volleyball,Silver,summer
104609,94052,"Kvtoslava ""Kvta"" Petkov",F,28.0,165.0,57.0,Czechoslovakia,TCH,1980,Moskva,Hockey,Hockey Women's Hockey,Silver,summer
104637,94338,Thomas Pfeffer,M,22.0,191.0,105.0,East Germany,GDR,1980,Moskva,Shooting,"Shooting Mixed Running Target, 50 metres",Silver,summer
104353,89730,Ann Osgerby,F,17.0,161.0,53.0,Great Britain,GBR,1980,Moskva,Swimming,Swimming Women's 4 x 100 metres Medley Relay,Silver,summer
104867,98094,Lajos Rcz,M,28.0,163.0,52.0,Hungary,HUN,1980,Moskva,Wrestling,"Wrestling Men's Flyweight, Greco-Roman",Silver,summer

In [35]:
##Summer medals count in absolute
summer_df["Medal"].value_counts(ascending = True)

Medal
Silver    11220
Bronze    11409
Gold      11459
Name: count, dtype: int64

In [34]:
##Summer medals in percentage
summer_df["Medal"].value_counts(normalize = True)

Medal
Gold      0.336159
Bronze    0.334693
Silver    0.329148
Name: proportion, dtype: float64

In [43]:
winter_df = df.query("Season == 'winter'")
winter_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
222552,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
222553,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
222554,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
222555,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
222556,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [37]:
##Winter medals count in absolute
winter_df["Medal"].value_counts(ascending = True)

Medal
Bronze    1886
Silver    1896
Gold      1913
Name: count, dtype: int64

In [38]:
##Winter medals in percentage
winter_df["Medal"].value_counts(normalize = True)

Medal
Gold      0.335909
Silver    0.332924
Bronze    0.331168
Name: proportion, dtype: float64

In [47]:
##All gold medals subset
gold_df = df.query("Medal == 'Gold'")
gold_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
6,4189,Nikolaos Andriakopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Gymnastics,Gymnastics Men's Rope Climbing,Gold,summer
19,12563,Conrad Helmut Fritz Bcker,M,25.0,NaN,NaN,Germany,GER,1896,Athina,Gymnastics,"Gymnastics Men's Parallel Bars, Teams",Gold,summer
21,12563,Conrad Helmut Fritz Bcker,M,25.0,NaN,NaN,Germany,GER,1896,Athina,Gymnastics,"Gymnastics Men's Horizontal Bar, Teams",Gold,summer
24,12929,John Mary Pius Boland,M,25.0,NaN,NaN,Great Britain,GBR,1896,Athina,Tennis,Tennis Men's Singles,Gold,summer
25,12929,John Mary Pius Boland,M,25.0,NaN,NaN,Great Britain/Germany,GBR,1896,Athina,Tennis,Tennis Men's Doubles,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271007,133782,Ruslan Albertovich Zakharov,M,26.0,173.0,72.0,Russia,RUS,2014,Sochi,Short Track Speed Skating,"Short Track Speed Skating Men's 5,000 metres R...",Gold,winter
271049,134463,Zhang Hong,F,25.0,174.0,65.0,China,CHN,2014,Sochi,Speed Skating,"Speed Skating Women's 1,000 metres",Gold,winter
271072,134824,Zhou Yang,F,22.0,165.0,62.0,China,CHN,2014,Sochi,Short Track Speed Skating,"Short Track Speed Skating Women's 1,500 metres",Gold,winter
271106,135343,Aleksandr Yuryevich Zubkov,M,39.0,189.0,102.0,Russia-1,RUS,2014,Sochi,Bobsleigh,Bobsleigh Men's Two,Gold,winter
271107,135343,Aleksandr Yuryevich Zubkov,M,39.0,189.0,102.0,Russia-1,RUS,2014,Sochi,Bobsleigh,Bobsleigh Men's Four,Gold,winter

In [50]:
##Top gold medals by country
top_gold_countries = gold_df["NOC"]
top_gold_countries

6         GRE
19        GER
21        GER
24        GBR
25        GBR
         ...
271007    RUS
271049    CHN
271072    CHN
271106    RUS
271107    RUS
Name: NOC, Length: 13372, dtype: str

In [55]:
top_gold_countries.head(10)

6     GRE
19    GER
21    GER
24    GBR
25    GBR
26    USA
27    USA
34    USA
35    USA
39    USA
Name: NOC, dtype: str

In [56]:
## return as percentage, rounded 2 decimal place

In [59]:
round(top_gold_countries.head(10).value_counts(normalize = True) * 100, 2)

NOC
USA    50.0
GER    20.0
GBR    20.0
GRE    10.0
Name: proportion, dtype: float64